spring: 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.65.131:3306/spring-boot-test?useUnicode=true&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
server:
  port: 9090
mybatis: 
  config-location: classpath:mybatis-config.xml