spring:
  datasource: 
    master: 
      jdbc-url: jdbc:mysql://192.168.65.131:3306/spring-boot-test?useUnicode=true&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用默认hikari连接池   springboot2 默认的  执行效率更高
      type: com.zaxxer.hikari.HikariDataSource
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 连接池名称
      pool-name: MyHikariCPOfMaster
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 20000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout=180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit=true
      ## 连接测试语句
      connection-test-query: SELECT 1
      validation-timeout: 5000
    slave: 
      jdbc-url: jdbc:mysql://192.168.65.131:3306/spring-boot-test?useUnicode=true&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 使用默认hikari连接池
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: MyHikariCPOfSlave
      max-lifetime: 1800000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      validation-timeout: 5000
server:
  port: 9090
mybatis:
  config-location: classpath:mybatis-config.xml
  #config-location: classpath:mybatis/mapper/*.xml
  #mapper-locations: classpath:mybatis/mapper/*.xml